# Generated by Django 5.2.6 on 2025-09-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='КНИГАtime', max_length=200)),
                ('site_subtitle', models.CharField(default='Путешествие во времени длиной в книгу', max_length=300)),
                ('header_background', models.ImageField(default='default_header.jpg', upload_to='site_settings/', verbose_name='Фон шапки')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
